spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/http-service-db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9093
    admin:
      auto-create: true
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
