spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/http-service-db
    username: postgres
    password: 123456
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9093
    admin:
      auto-create: true
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
