version: '3.8'

services:
  worker-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    ports:
      - "8082:8082"